### ISSUE TITLE
图片的大小和原尺寸不一致

### ISSUE THREAD

**Issue by hyh19962008** [flytkgl/PDFQFZ#1]
RT，软件会自动拉伸放大图片到一个固定的尺寸，具体拉伸的大小和原图片尺寸无关……

**Comment by flytkgl** [comment]
我代码只是把图片做了等份分割，没有调整图片大小啊

**Comment by hyh19962008** [comment]
你试试用不同的文件测试一下，反正我换了几张图片和PDF都会这样

**Comment by mimicao** [comment]
原因应该是图片是使用的像素大小，而PdfReader()读取是以72dpi来读取pdf文档的像素。通过实际需要的图片大小(毫米/厘米)，再通过72dpi计算出需要插入图片的像素在重新编辑图片像素，应该就解决了。

**Comment by mimicao** [comment]
以4cm公章为例，其72dpi下的pixel为113，可以使用清晰的图片，重新缩放图片比例大小。          
//水印的位置
image.ScaleToFit(113f/numberOfPages, 113f);
image.SetAbsolutePosition(width-113f/numberOfPages, (height - 113f) / 2);

不确定是否有更好的方法来进行处理。

**Comment by btwise** [comment]
> 以4cm公章为例，72dpi下的像素为113，可以使用清晰的图片，放大其缩放图片比例大小。
> //水印的位置
> image.ScaleToFit(113f/numberOfPages, 113f);
> image.SetAbsolutePosition(width-113f/numberOfPages, (height - 113f) / 2);
> 
> 是否有更好的方法来进行处理。

能否完善一下整体代码，目前确实无法实现盖章

**Comment by flytkgl** [comment]
> > 以4cm公章为例，72dpi下的像素为113，可以使用清晰的图片，放大其缩放图片比例大小。
> > //水印的位置
> > image.ScaleToFit(113f/numberOfPages, 113f);
> > image.SetAbsolutePosition(width-113f/numberOfPages, (height - 113f) / 2);
> > 是否有更好的方法来进行处理。
> 
> 能否完善一下整体代码，目前确实无法实现盖章

这个工具还有人在用吗......当时我们采购的同事有需求顺手帮忙写的,后面辞职了同事也没跟我反馈过问题就没有再关注了

**Comment by flytkgl** [comment]
> 以4cm公章为例，其72dpi下的pixel为113，可以使用清晰的图片，重新缩放图片比例大小。
> //水印的位置
> image.ScaleToFit(113f/numberOfPages, 113f);
> image.SetAbsolutePosition(width-113f/numberOfPages, (height - 113f) / 2);
> 
> 不确定是否有更好的方法来进行处理。

普通图片的dpi一般是72,而打印一般需要300dpi,所以我现在是做了个24%的缩放,看起来应该是差不多

**Comment by flytkgl** [comment]
> > 以4cm公章为例，72dpi下的像素为113，可以使用清晰的图片，放大其缩放图片比例大小。
> > //水印的位置
> > image.ScaleToFit(113f/numberOfPages, 113f);
> > image.SetAbsolutePosition(width-113f/numberOfPages, (height - 113f) / 2);
> > 是否有更好的方法来进行处理。
> 
> 能否完善一下整体代码，目前确实无法实现盖章

已修复,随便解决了其他几个小问题
