### ISSUE TITLE
合并功能报错

### ISSUE THREAD

**Issue by svcvit** [flytkgl/PDFQFZ#10]
![Xnip2022-06-23_21-48-32](https://user-images.githubusercontent.com/3839507/175315028-e5abdf9c-d4fd-46c8-81ed-20837a641755.jpg)

启用合并模式，报了个错。非合并模式正常。

**Comment by flytkgl** [comment]
有行测试代码忘了删了
代码已修复,你可以自己编译下或者等我有空发布个编译版
也可以在自己电脑新建如下目录就不会报错了
D:\tmp\img

**Comment by svcvit** [comment]
电脑没有D盘，我等之后的更新的release，感谢~
