### ISSUE TITLE
印章文件记录保持

### ISSUE THREAD

**Issue by wyongjian** [flytkgl/PDFQFZ#13]
这是个很棒的工具，有一点使用的时候不是很方便，就是每次都需要选择图章所在的路径，是否可以保存最后一个？或者保存历史记录，下拉选择。
再次感谢作者的无私贡献。

**Comment by flytkgl** [comment]
> 这是个很棒的工具，有一点使用的时候不是很方便，就是每次都需要选择图章所在的路径，是否可以保存最后一个？或者保存历史记录，下拉选择。 再次感谢作者的无私贡献。

已更新为下拉选择

**Comment by wyongjian** [comment]
更新了很方便了，非常感谢。
