### ISSUE TITLE
可不可弄成网页版的，部署在centos、docker这种，盖过章的文件会保存在服务器上。

### ISSUE THREAD

**Issue by zkzcw** [flytkgl/PDFQFZ#14]
软件很好用，有个小小建议，可不可弄成网页版的，部署在centos、docker这种，盖过章的文件会保存在服务器上。

**Comment by flytkgl** [comment]
> 软件很好用，有个小小建议，可不可弄成网页版的，部署在centos、docker这种，盖过章的文件会保存在服务器上。

这工具是用C#写的,还调用了两个库,想运行在centos、docker上大概是比较困难的,运行在Windows服务器上提供个API接口供网页或其他程序调用相对比较简单一点.要不你Fork一份自己改下(斜眼笑

**Comment by zkzcw** [comment]
完全不懂编程，windows也可以啊，就是占用资源大一点而已。哈哈哈

**Comment by svcvit** [comment]
> 软件很好用，有个小小建议，可不可弄成网页版的，部署在centos、docker这种，盖过章的文件会保存在服务器上。

https://github.com/svcvit/stitchweb 写了一个，分享用用。
