### ISSUE TITLE
使用证书签名后，印章的不透明度设置和旋转设置均失效

### ISSUE THREAD

**Issue by LEIRONGHUA** [flytkgl/PDFQFZ#15]
如题，印章文件为png格式的图片，如果不用证书签名，那么可以实现不透明度功能和旋转设置功能，印章增加真实。
但是如果启用了证书签名，不透明度设置和旋转设置均失效了。
而且签名出来的文件，签名显示由“某某某而”签名，是乱码，如图所示：
![image](https://user-images.githubusercontent.com/4002277/224357254-5d92cbec-8caf-4ca4-aac2-8336374107c0.png)

**Comment by flytkgl** [comment]
我这边测试使用数字签名的情况下旋转和不透明度都是正常的哦,签名显示乱码的问题感觉是WPS对于中文自签名证书的支持有问题,我使用英文的签名显示就是正常的,而使用Adobe查看的话,无论是中文还是英文都正常

**Comment by LEIRONGHUA** [comment]
应该是PDFQFZ.exe生成的自签名证书格式不兼容吧。
用WPS的PDF保护功能，产生的自签名证书是可以显示正常的中文。
数字签名的情况下旋转和不透明度都是正常的，我这边搞错了。
