### ISSUE TITLE
是否可以实现骑缝章自定义页面

### ISSUE THREAD

**Issue by btwise** [flytkgl/PDFQFZ#18]
一些时候需要双面打印，需要骑缝章自定义页面，根据指定页面重新计算分割图章份数！

**Comment by flytkgl** [comment]
你意思是单数页做一个骑缝章，双数页再做一个骑缝章？

**Comment by btwise** [comment]
> 你意思是单数页做一个骑缝章，双数页再做一个骑缝章？

不是，意思是加一个选项，可以自定义选择哪些页面加骑缝章，比如1，3，4，6或者2-7随便自定义加骑缝章

**Comment by flytkgl** [comment]
> > 你意思是单数页做一个骑缝章，双数页再做一个骑缝章？
> 
> 不是，意思是加一个选项，可以自定义选择哪些页面加骑缝章，比如1，3，4，6或者2-7随便自定义加骑缝章

无法理解你的使用场景，而且这种操作在多文件的情况下会有问题吧

**Comment by btwise** [comment]
> > > 你意思是单数页做一个骑缝章，双数页再做一个骑缝章？
> > 
> > 
> > 不是，意思是加一个选项，可以自定义选择哪些页面加骑缝章，比如1，3，4，6或者2-7随便自定义加骑缝章
> 
> 无法理解你的使用场景，而且这种操作在多文件的情况下会有问题吧

只在单文件模式下使用，比如进行双面打印时候，只需要在奇数页上有骑缝章，或者不在封面第一页加骑缝章

**Comment by richmondming** [comment]
今天为啥出错失效了

**Comment by flytkgl** [comment]
> > > > 你意思是单数页做一个骑缝章，双数页再做一个骑缝章？
> > > 
> > > 
> > > 不是，意思是加一个选项，可以自定义选择哪些页面加骑缝章，比如1，3，4，6或者2-7随便自定义加骑缝章
> > 
> > 
> > 无法理解你的使用场景，而且这种操作在多文件的情况下会有问题吧
> 
> 只在单文件模式下使用，比如进行双面打印时候，只需要在奇数页上有骑缝章，或者不在封面第一页加骑缝章

已更新支持随意骑缝章
