### ISSUE TITLE
骑缝章无法实现

### ISSUE THREAD

**Issue by btwise** [flytkgl/PDFQFZ#2]
我更改公章大小为40mm，程序执行后生成的pdf上无法看到效果，能否完善一下

**Comment by flytkgl** [comment]
更新了一个版本,请验证是否已修复

**Comment by btwise** [comment]
> 更新了一个版本，请验证已修复

明天我测试一下，这个工具很有用的，能实现单页盖章和一次选取坐标自动多页相同位置盖章，加上骑缝章，这样就更好了

**Comment by btwise** [comment]
这个版本测试可以正常工作，但不同的PDF文件，盖章的位置并不一致，建议增加**自定义坐标位置功能，图章大小自定义尺寸，增加单页和多页盖章**功能！

**Comment by flytkgl** [comment]
> 这个版本测试可以正常工作，但不同的PDF文件，盖章的位置并不一致，建议增加**自定义坐标位置功能，图章大小自定义尺寸，增加单页和多页盖章**功能！

盖章位置不一致这个有图吗,代码是按(文档高度-印章高度)/2来定位的,正常都会靠右居中才对

**Comment by btwise** [comment]
> > 这个版本测试可以正常工作，但不同的PDF文件，盖章的位置并不一致，建议增加**自定义坐标位置功能，图章大小自定义尺寸，增加单页和多页盖章**功能！
> 
> 盖章位置不一致这个有图吗,代码是按(文档高度-印章高度)/2来定位的,正常都会靠右居中才对

骑缝章应该是同时计算宽度吧，我测试了一个两张页面的文档，它并没有盖到最右边边上

**Comment by flytkgl** [comment]
> > > 这个版本测试可以正常工作，但不同的PDF文件，盖章的位置并不一致，建议增加**自定义坐标位置功能，图章大小自定义尺寸，增加单页和多页盖章**功能！
> > 
> > 
> > 盖章位置不一致这个有图吗,代码是按(文档高度-印章高度)/2来定位的,正常都会靠右居中才对
> 
> 骑缝章应该是同时计算宽度吧，我测试了一个两张页面的文档，它并没有盖到最右边边上

宽度就是文档宽度-印章宽度,我这边测试的文件都是正常的,除非你PDF页面有旋转,刚好最新更新的一个版本有修复这个问题,另外你提的自定义坐标和大小也加上了,你可以看下

**Comment by btwise** [comment]
好的，辛苦了，如果选择的图章大小不是标准尺寸，是否可以自定义图章大小或使用标准公章尺寸？

**Comment by flytkgl** [comment]
> 好的，辛苦了，如果选择的图章大小不是标准尺寸，是否可以自定义图章大小或使用标准公章尺寸？

可以自己调整图章缩放比例,不过图片dpi一般是72,而PDF的dpi一般在300以上,所以标准公章尺寸也应该缩放到24%

**Comment by btwise** [comment]
盖章效果和缩放不错，如果是单页的话，是不需要骑缝章的，所以下拉列表框应该增加单页盖章的选项，旁边可以增加一个是否加盖骑缝章的单选项(不是所有的文档都需要骑缝章)

**Comment by flytkgl** [comment]
> 盖章效果和缩放不错，如果是单页的话，是不需要骑缝章的，所以下拉列表框应该增加单页盖章的选项，旁边可以增加一个是否加盖骑缝章的单选项(不是所有的文档都需要骑缝章)

小工具还是希望做的尽量简洁的,不想添加这么多自定义设置,刚更新了个版本排除了单页加盖骑缝章的情况,另外优化了下印章的比例
