### ISSUE TITLE
为什么页数多的pdf会盖2遍甚至3遍？

### ISSUE THREAD

**Issue by ttpcy** [flytkgl/PDFQFZ#20]
问了下公司商务好像盖骑缝章没有这个规矩，是程序有页数限制吗？

**Comment by flytkgl** [comment]
因为一个骑缝章分太多份就完全看不清了,所以程序限制了最多分割20份,超过就会拆分成多个骑缝章

**Comment by ttpcy** [comment]
明白了，不过确实和实际不太相符，公司几百页的标书也都是盖一个章。
如果实现不复杂，建议可以考虑修改一下
