### ISSUE TITLE
PDF加盖骑缝章

### ISSUE THREAD

**Issue by sycpiek** [flytkgl/PDFQFZ#21]
少量的文件加盖印章是正常的非常不错，
但是文件页数一多就超出了印章的范围 骑缝章就变成了循环的。
一个意见是，能不能用GIF格式的印章，因为GIF的印章空白处是透明的，jpg和png都是白色的会遮挡文字

**Comment by sycpiek** [comment]
应该是超过18页就会循环

**Comment by flytkgl** [comment]
GIF是动图,png是支持透明背景的,jpg不支持透明背景但是可以用小工具调整整体的透明度,就是效果没png的透明背景好,骑缝章

**Comment by flytkgl** [comment]
> 应该是超过18页就会循环

已支持自定义设置骑缝章最大分割数
