### ISSUE TITLE
旋转印章会改变印章大小，能不能在旋转时保持其尺寸不变？

### ISSUE THREAD

**Issue by trump888** [flytkgl/PDFQFZ#23]
旋转印章会改变印章大小，能不能在旋转时保持其尺寸不变？

**Comment by flytkgl** [comment]
在旋转印章时是有做切边处理的,正常来说是不会原尺寸的

**Comment by trump888** [comment]
当印章图片为正方形时旋转没有问题，当印章图片为长方形时旋转就会切掉大半
测试图片：

![test](https://github.com/flytkgl/PDFQFZ/assets/87228191/abdde517-052f-4e3d-96c2-1bf05f8d67d6)

**Comment by trump888** [comment]
像pdf-xchange等是可以做到尺寸不变的

**Comment by flytkgl** [comment]
程序是基于图片中心来旋转的,所以只能支持圆形或椭圆形并且印章在正中位置的图片,不支持方形印章或非正中位置印章的旋转
因为方形印章要求的是扩大长宽来保留完整的图片内容,这种情况如果放到椭圆形的图片会导致印章白边增多,在盖骑缝章时可能会出现首页或尾页只盖到了白边的情况
所以如果是方形印章或者非中间位置的印章建议还是先自己处理下

**Comment by trump888** [comment]
能否将是否切边做成一个用户选项框，可以避免一刀切

**Comment by flytkgl** [comment]
其实改起来很简单,只需要添加一个下拉框,然后在切边的地方判断一下就好了,要不你帮忙提个pull(逃~

**Comment by flytkgl** [comment]
已更新支持
