### ISSUE TITLE
可否可以使用 cmd 以命令行 提供参数，静默执行

### ISSUE THREAD

**Issue by tenxs** [flytkgl/PDFQFZ#24]

**Comment by flytkgl** [comment]
没研究过这方面的内容,待我先学习下,等学会了就加上

**Comment by tenxs** [comment]
非常感谢！ 在有视图界面当点击更改默认印章位置的时候，因该会返回一个点击位置； 把这个点击位置也作为参数传递进去，就不需要手工定位印章所在位置。因该是这样，谢谢！

**Comment by tenxs** [comment]
稍微包装一下，就可以作为NPM 包发布了，这功能因该有不少需求，帮助很多人。

**Comment by flytkgl** [comment]
> 非常感谢！ 在有视图界面当点击更改默认印章位置的时候，因该会返回一个点击位置； 把这个点击位置也作为参数传递进去，就不需要手工定位印章所在位置。因该是这样，谢谢！

你这是把他当成一个后端程序,打算通过前端传参吧,可惜他是一个winfrom的桌面程序,没法发布到NPM,通过CMD命令行也只能传几个字符串的参数.所以你的想法大概是实现不了的.倒是可以考虑给它内置一个http的库,这样就可以通过网络调用了
