### ISSUE TITLE
能否增加对加密 pdf 文档的支持

### ISSUE THREAD

**Issue by fseteen** [flytkgl/PDFQFZ#25]
感谢作者无私付出。使用效果非常好！
请问有否考虑增加对加密 pdf 文档的支持？
目前需要先解除文档保护后才能进行骑缝处理。希望界面可以增加加密文档识别，并支持解密（目前我用的是密码，不排除有使用密钥的用户）输入。

**Comment by flytkgl** [comment]
这个有空研究一下

**Comment by flytkgl** [comment]
已更新支持加密PDF
