### ISSUE TITLE
印章大小根据每页文档尺寸可以自定义

### ISSUE THREAD

**Issue by btwise** [flytkgl/PDFQFZ#29]
@flytkgl 
如果当一个PDF文档里的每一页不同的时候，比如有A4,A3,A1等不同大小，如果印章大小相同，则比例很不协调，可否增加自定义盖章时候，印章尺寸也可以根据页面尺寸进行自定义设置

**Comment by flytkgl** [comment]
每页的纸张大小不一致,然后导致印章的大小也不一致才是合理的吧,感觉没毛病啊

**Comment by flytkgl** [comment]
已支持设定PDF的dpi,不过只支持统一设定,不支持按每页设定,正常扫描件就算是A4,A3等不同纸张,只要是一起扫的,那DPI应该也是一样的,所以应该是不需要按页设置DPI的
