### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by xuexiaokang** [flytkgl/PDFQFZ#31]
盖章选“合并”就会导致盖章后的文件乱码
![Snipaste_2023-12-13_15-19-05](https://github.com/flytkgl/PDFQFZ/assets/9048178/e657af4e-f38b-42e2-9711-0ffa34220f6a)
![Snipaste_2023-12-13_15-18-46](https://github.com/flytkgl/PDFQFZ/assets/9048178/45391ed2-e839-468d-83ba-8c51a65e3486)

**Comment by flytkgl** [comment]
右边预览的时候就是乱码的吗,那可能是用的库无法识别你PDF的字体,最好能提供个乱码的PDF我研究下如何解决这兼容性问题,不然我没法复现也不太好处理

**Comment by xuexiaokang** [comment]
> 右边预览的时候就是乱码的吗,那可能是用的库无法识别你PDF的字体,最好能提供个乱码的PDF我研究下如何解决这兼容性问题,不然我没法复现也不太好处理

[测试文件.pdf](https://github.com/flytkgl/PDFQFZ/files/14532439/default.pdf)
只要是选择合并，出来的文件就是这样乱码

**Comment by xintiandi** [comment]
> > 右边预览的时候就是乱码的吗,那可能是用的库无法识别你PDF的字体,最好能提供个乱码的PDF我研究下如何解决这兼容性问题,不然我没法复现也不太好处理
> 
> [测试文件.pdf](https://github.com/flytkgl/PDFQFZ/files/14532439/default.pdf) 只要是选择合并，出来的文件就是这样乱码

你这个是系统缺少STSong-Light字体，到百度上搜索一下STSong-Light字体，下载放到系统font目录下，重新打开盖章软件就可以了。有些第三方pdf工具，比如福昕可以正常识别字体。

**Comment by flytkgl** [comment]
[STSong-Light.zip](https://github.com/user-attachments/files/17006518/STSong-Light.zip)
经测试安装这个字体后正常
