### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by colalall** [flytkgl/PDFQFZ#32]
1.新版本盖章出来的效果好像没有以前那么真实了
2.有些比较深色的印章盖章后章子变得有些模糊

**Comment by flytkgl** [comment]
你改了透明度吧，不然跟原来应该是没区别的啊

**Comment by colalall** [comment]
透明度一般都是需要改的，正常盖章文件黑子字体是会透过印章显示的，不改透明度直接盖章，印章把黑色字体盖住，有一点假，客户有些公司或客户会有意见

**Comment by flytkgl** [comment]
我的建议是,印章图片用PNG格式,背景透明印章不透明,然后通过小工具来调整整体的透明度,个人测试这样效果会比较好

**Comment by colalall** [comment]
一直使用的png格式的印章图片，调整了不透明度以后，发现颜色反而印章的颜色变的更深，印章更模糊了，100%不透明没有问题

**Comment by flytkgl** [comment]
那你可以尝试直接调整印章图片的透明度,然后小工具的不透明度设置为100%看下
