### ISSUE TITLE
启动建议

### ISSUE THREAD

**Issue by jin19910128** [flytkgl/PDFQFZ#33]
1.通过拖拽文件到exe启动程序上作为首次启动参数
2.增加右键快速启动选项，这样不用每次启动都先找软件

**Comment by flytkgl** [comment]
1已经支持了吧，你把文件拖到待盖章文件的那个输入框就好了
2的话需要动注册表，这不太符合绿色软件的定位啊

**Comment by flytkgl** [comment]
你提到的这两个应该已经支持了,不改注册表,直接右键选择打开方式
