### ISSUE TITLE
自定义盖章建议

### ISSUE THREAD

**Issue by chaes666** [flytkgl/PDFQFZ#38]
在自定义盖章时,希望能出一个输入页数自动跳转页的设计.如窗口右上角显示页码的位置.可以手动更改页数.这样方便那种上百页但只盖几外地方的情况.如果没有定位页数的话,鼠标点下一页得点哭....

**Comment by flytkgl** [comment]
下次优化....

**Comment by flytkgl** [comment]
已支持下拉选择跳转到指定页
