### ISSUE TITLE
自定义盖章及每页不同角度

### ISSUE THREAD

**Issue by Flyingrabbita** [flytkgl/PDFQFZ#41]
自定义盖章还得麻烦大佬有时间优化一下  文件多的话一页一页点太累了

**Comment by flytkgl** [comment]
已支持每页的印章都随机加一个旋转角度

**Comment by flytkgl** [comment]
因为现在改成了预览PDF的时候一次性读取所有页,这样就会导致如果文件页很多的话会很卡,但是读取完后翻页就很流畅,不像之前会卡一下下

**Comment by Flyingrabbita** [comment]
感谢感谢&nbsp; 那我明白了&nbsp; 的确是文件有点大&nbsp; 麻烦您嘞
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "flytkgl/PDFQFZ"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月5日(星期三) 晚上6:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [flytkgl/PDFQFZ] 自定义盖章及每页不同角度 (Issue #41)





 
因为现在改成了预览PDF的时候一次性读取所有页,这样就会导致如果文件页很多的话会很卡,但是读取完后翻页就很流畅,不像之前会卡一下下

**Comment by Flyingrabbita** [comment]
已下载下来了&nbsp; 感谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "flytkgl/PDFQFZ"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月5日(星期三) 晚上6:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [flytkgl/PDFQFZ] 自定义盖章及每页不同角度 (Issue #41)





 
因为现在改成了预览PDF的时候一次性读取所有页,这样就会导致如果文件页很多的话会很卡,但是读取完后翻页就很流畅,不像之前会卡一下下
