### ISSUE TITLE
遇到一个高分辨pdf文件，盖的骑缝章很小，不知道算不算bug

### ISSUE THREAD

**Issue by xintiandi** [flytkgl/PDFQFZ#43]
pdf文件是几张图片合成的，图片文件都是4000*3000多，骑缝章改后，骑缝章变得很小，不知道算不算bug，我看章可以设置尺寸，是否增加一个页面比例的功能，根据当前页面来算大小，最后我用应急方案时，找一个正常的pdf导出成图片看分辨率大小，把之前的图片按照导出的图片分辨率修改后，重新合成pdf再盖骑缝章，这样就正常了。

**Comment by xintiandi** [comment]
刚才修改了一下源码，当高分文件时，加了一个自动缩放印章选项，不勾，则安装实际像素尺寸计算，印章和骑缝章同时处理，算是解决了，
                if (yzType!=0|| qmType != 0)
                {
                    iTextSharp.text.Image img = null;
                    float imgW=0, imgH=0;
                    float xPos=0, yPos=0;
                    bool all = false;
                    int signpage = 0;

                    if (yzType != 0)
                    {
                        img = iTextSharp.text.Image.GetInstance(imgYz, System.Drawing.Imaging.ImageFormat.Png);

                        //最终完美兼容2种情况的方法
                        float scale;
                        if (checkBoxDPI.Checked) // 高分辨率 PDF 文档 resolution > 300
                        {
                            scale = GetWatermarkScale(pdfReader.GetPageSize(1), imgYz); // 
                            img.ScalePercent(scale * 100f);
                            imgW = img.Width * scale;
                            imgH = img.Height * scale;
                        }
                        else // 低分辨率 PDF 文档
                        {
                            img.ScalePercent(sfbl);
                            imgW = img.Width * sfbl / 100f;
                            imgH = img.Height * sfbl / 100f;
                            //scale = GetWatermarkScale(psize, qfzImage, 0.20f); // 高分屏设置了缩放比例，反而不正常
                        }
                    }

**Comment by flytkgl** [comment]
何不直接提个PR

**Comment by xintiandi** [comment]
> 何不直接提个PR

还不会用github提交pr，我是遇到问题才去处理，等空闲的时候学习一下

**Comment by flytkgl** [comment]
已支持设定PDF的dpi

**Comment by xintiandi** [comment]
> 已支持设定PDF的dpi

感谢这么快就修复，最近比较忙，都没有注意更新了2个版本了。
暂时还不会pr，希望有机会也为开源做点贡献，下面是之前的修改的版本，看还有没有可用的地方
[Form1.zip](https://github.com/user-attachments/files/15863732/Form1.zip)
