### ISSUE TITLE
建议在每页都盖章的功能更细化

### ISSUE THREAD

**Issue by lrbin50** [flytkgl/PDFQFZ#48]
可以细化为除指定页（一般为最后或第一页）指定到特定位置，中间页的盖章可以有限定的小范围随机位置的移动及角度的变换（更接近实际，不可能每页盖章都这么精确！）

**Comment by flytkgl** [comment]
多页印章的位置是可以自定义的啊，只是所有页印章时如果你没有定义这一页的位置就会默认为最后一次定位的位置，而且现在多页印章默认就是±10°随机旋转角度的了

**Comment by lrbin50** [comment]
哦，有10%的随机旋转角度不错，没注意，我知道位置是可以定义。我意思中间的页不是定义准确的位置，而是一个小范围的位置可以随机移动的，就像随机角度一样。

**Comment by flytkgl** [comment]
> 哦，有10%的随机旋转角度不错，没注意，我知道位置是可以定义。我意思中间的页不是定义准确的位置，而是一个小范围的位置可以随机移动的，就像随机角度一样。

由于软件不支持每页的旋转角度，所以设定一个随机角度值我觉得是合理的。但是每页的印章位置都是由用户自己决定的，再搞个随机偏移我觉得大可不必

**Comment by Hezixuebi** [comment]
我觉得还是随机偏移还是有必要的啊，虽然可以自己设置每一页的印章位置，但是如果太多页，不想每页都自己调位置，但又不想每页都在同一位置，这个功能有了会更好🤣

**Comment by flytkgl** [comment]
> 我觉得还是随机偏移还是有必要的啊，虽然可以自己设置每一页的印章位置，但是如果太多页，不想每页都自己调位置，但又不想每页都在同一位置，这个功能有了会更好🤣

已优化
