### ISSUE TITLE
自选页盖章

### ISSUE THREAD

**Issue by btwise** [flytkgl/PDFQFZ#5]
有的时候，需要在指定的页面盖章，能否实现任意页自定义盖章？

**Comment by flytkgl** [comment]
自定义页盖章跟多文件批量处理不太兼容，现在程序是最后一次点击的印章位置会应用到其他所有未定义位置的页，要自定义页盖章的话就只能一页一页设置印章位置，没设置的就不盖。感觉使用起来比较麻烦就没做

**Comment by flytkgl** [comment]
自定义页盖章跟多文件批量处理不太兼容，现在程序是最后一次点击的印章位置会应用到其他所有未定义位置的页，要自定义页盖章的话就只能一页一页设置印章位置，没设置的就不盖。感觉使用起来比较麻烦就没做

**Comment by btwise** [comment]
@flytkgl 很高兴看到你增加了自定义页面盖章的功能，但如果鼠标误点了预览画面，这时候应该增加自定义页面删除某个页面的图章的功能!

**Comment by flytkgl** [comment]
> @flytkgl 很高兴看到你增加了自定义页面盖章的功能，但如果鼠标误点了预览画面，这时候应该增加自定义页面删除某个页面的图章的功能!

已添加,在需要删除印章的页面双击印章即可
