### ISSUE TITLE
导入多页数PDF加载时间较长且出现未响应

### ISSUE THREAD

**Issue by bingsunny0730** [flytkgl/PDFQFZ#50]
几页还好，新版本导入三百多页的文件直接卡到无响应，需要等待数几分钟才能恢复，有点不方便，希望改进
![sshot-2024-08-01- 17-20-23](https://github.com/user-attachments/assets/9f7739c3-8226-4fa6-a061-38c48a97feb6)

**Comment by flytkgl** [comment]
这个需要改成多线程读取才能提升速度。最近比较忙，还没时间改

**Comment by flytkgl** [comment]
已优化
