### ISSUE TITLE
请问，怎么查看PDF的DPI，每次都要确认pdf文件的DPI吗？

### ISSUE THREAD

**Issue by kimijoan** [flytkgl/PDFQFZ#51]
我在网上查了有说需要PS查看的，有说PDF文件不涉及DPI的。
请问怎么看PDF文件分辨率。一般用到的PDF文件，扫描的图片PDF文件和文档导出的文字PDF都有。

**Comment by flytkgl** [comment]
扫描成PDF文件的时候可以设置分辨率的，一般有100/200/300/400/600dpi这几个值，可能用200的比较多
