### ISSUE TITLE
请问 能否 一个骑缝章 覆盖所有 页面?  目前 25页 第1,13,和25页 没有骑缝章印记

### ISSUE THREAD

**Issue by GOLDROBERT** [flytkgl/PDFQFZ#52]
2-12 和 14-24 分别盖了一个骑缝章. 而第1页 ,最后的第25页, 和 第13页 没有, 

想要一个骑缝章盖到25页 可能实现吗

**Comment by flytkgl** [comment]
第一个问题:印章图片不要有白边
第二个问题:你猜"骑缝章最大分割数"这个参数是干嘛用的

**Comment by GOLDROBERT** [comment]
感谢答复. 
1. 确实
2. pdf 显示总页数25. 分割数26.可以达到效果. 分割数放25就分成2个章了. 
3. 好像不是平均分, 最后一页章的部分会明显大一些. 就是的这样设定吗?

再次感谢作者, 不用浪费纸 盖错 又重打印了~

**Comment by flytkgl** [comment]
2.你可以设置成1000，这样少于1000页的就都是一个骑缝章了
3.是的，第一个和最后一个骑缝章会留大一点，中间的随机大小
