### ISSUE TITLE
求MacBook版

### ISSUE THREAD

**Issue by openbilly** [flytkgl/PDFQFZ#54]
在PC下太好用啦，但平时只带着MacBook外出，真心希望有MacBook版的。

**Comment by flytkgl** [comment]
但是我没有MacBook,也不会写MacBook的软件啊,还是让其他大佬出手吧

**Comment by btwise** [comment]
> 在PC下太好用啦，但平时只带着MacBook外出，真心希望有MacBook版的。

已经重写，支持macos和linux
