### ISSUE TITLE
太有趣了，如果能有Mac版本就完美了

### ISSUE THREAD

**Issue by shruru** [flytkgl/PDFQFZ#55]
希望能有一个Mac系统的版本~👍🏻

**Comment by shog86** [comment]
+1

**Comment by flytkgl** [comment]
不会MAC开发,目前也无此计划,这问题有请其他大佬

**Comment by btwise** [comment]
> 希望能有一个Mac系统的版本~👍🏻

已经实现macos和linux版本，有需要私信联系

**Comment by btwise** [comment]
> [@btwise](https://github.com/btwise)能发一个给我吗

https://cowtransfer.com/s/d7c7e7a8d76142点击链接查看[ PSDStamp_MacOS ] ，或访问奶牛快传cowtransfer.com输入传输口令 y3bnp2

**Comment by shog86** [comment]
> > [@btwise](https://github.com/btwise)能发一个给我吗
> 
> [https://cowtransfer.com/s/d7c7e7a8d76142点击链接查看[](https://cowtransfer.com/s/d7c7e7a8d76142%E7%82%B9%E5%87%BB%E9%93%BE%E6%8E%A5%E6%9F%A5%E7%9C%8B%5B) PSDStamp_MacOS ] ，或访问奶牛快传cowtransfer.com输入传输口令 y3bnp2

感谢兄弟增加Mac版，但怎么还要注册啊，作者原版Win版我看截图是没有限制功能的呀。

cc @flytkgl 求官方mac版

**Comment by btwise** [comment]
虽然界面差不多，但这是重新写的，联系微信免费给你注册发自我的手机-------- 原始邮件 --------发件人： zhongjun_ge ***@***.***>日期： 2025年2月2日周日 11:46收件人： flytkgl/PDFQFZ ***@***.***>抄送： btwise ***@***.***>, Mention ***@***.***>主    题： Re: [flytkgl/PDFQFZ] 太有趣了，如果能有Mac版本就完美了 (Issue #55)


@btwise能发一个给我吗

[https://cowtransfer.com/s/d7c7e7a8d76142点击链接查看 PSDStamp_MacOS ] ，或访问奶牛快传cowtransfer.com输入传输口令 y3bnp2

感谢兄弟增加Mac版，但怎么还要注册才能用部分功能啊，作者原版Win版我看截图是没有限制功能的呀。
cc @flytkgl 求官方mac版

**Comment by shog86** [comment]
> 虽然界面差不多，但这是重新写的，联系微信免费给你注册发自我的手机-------- 原始邮件 --------发件人： zhongjun_ge ***@***.***>日期： 2025年2月2日周日 11:46收件人： flytkgl/PDFQFZ ***@***.***>抄送： btwise ***@***.***>, Mention ***@***.***>主    题： Re: [flytkgl/PDFQFZ] 太有趣了，如果能有Mac版本就完美了 (Issue #55)
> 
> 
> 
> 
> 
> @btwise能发一个给我吗
> 
> 
> 
> [https://cowtransfer.com/s/d7c7e7a8d76142点击链接查看 PSDStamp_MacOS ] ，或访问奶牛快传cowtransfer.com输入传输口令 y3bnp2
> 
> 
> 
> 感谢兄弟增加Mac版，但怎么还要注册才能用部分功能啊，作者原版Win版我看截图是没有限制功能的呀。
> 
> cc @flytkgl 求官方mac版
> 
> 
> 
> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

怎么发你机器码？
