### ISSUE TITLE
2个问题反馈

### ISSUE THREAD

**Issue by bingbaicai** [flytkgl/PDFQFZ#56]
软件是今天刚下载的最新版本
问题1:
这个文件有500多页，文件能成功盖章，但是软件后面卡死，见附图
![QQ截图20240902145919](https://github.com/user-attachments/assets/f77a8b97-ecf3-4cf2-add7-8a97fb443c96)
问题2:
盖了骑缝的PDF选择打印的时候必须选择适合打印边距才能显示公章，这样打印出来的公章有个问题：他右边还有空白的显示

**Comment by bingbaicai** [comment]
问题2的补充，他在PDF里面显示章是如截图布满到页边了，但是打印出来的他右边还有空白的，就失真了
![QQ截图20240902151439](https://github.com/user-attachments/assets/de44f553-c9a3-47dd-bcb9-2f977111297c)

**Comment by bingbaicai** [comment]
问题2我发现打印机里面还有个设置页边距，我把他设置成0还不行，
应该如何解决这个问题呢？大佬

**Comment by flytkgl** [comment]
问题1可能是因为你没等文件的所有页面读取完导致的
问题2是打印机的问题,打印最小边距必须大于2mm,我请教过做打印机的人,大部分打印机是是不支持设置为0的,不然容易卡纸

**Comment by bingbaicai** [comment]
问题2那就是目前还没法解决啊o(╥﹏╥)o
