### ISSUE TITLE
期望能提供 WEB 版本

### ISSUE THREAD

**Issue by zsinba** [flytkgl/PDFQFZ#58]
桌面版本只能 Windows 用； Macos 并不好用； 
另外，印章管理也不太好放在某个共享机器上，如果能通过 web 来跑，就可以进一步开发为控制个人账号、企业账号、对接外部系统行装； 那整个系统的扩展性和发展方向就比较大了； 
当前就仅是桌面版本，发展空间有限。

**Comment by flytkgl** [comment]
本来的定位就是便捷小工具,无意往高大全的系统发展,所以你可以再看看其他大佬的版本

**Comment by zsinba** [comment]
很好的工具，有用！
谢谢分享
