### ISSUE TITLE
印章清晰度能不能自定义呢

### ISSUE THREAD

**Issue by errorcheng** [flytkgl/PDFQFZ#6]
之前用的V1.2版本，加盖的电子印章很清晰，最新V1.8版本，印章做了模糊处理，这个清晰度能否自定义呢，现在的模糊的有点过了。

**Comment by errorcheng** [comment]
dpi能够修改

**Comment by flytkgl** [comment]
> dpi能够修改

这是因为电脑显示图片跟PDF图片的DPI不一样,之前是按PDF的DPI来显示的,会比电脑上看的小很多,所以后面改成了按电脑显示的DPI.其实提示有说明的,你只需要提供个高清点的印章图片,然后调整缩放比例或者直接指定印章尺寸就可以了

**Comment by flytkgl** [comment]
另外不太确定你说的模糊是不是因为添加印章时默认设置了0.4的透明度导致的

**Comment by flytkgl** [comment]
我这边看了下提交记录,大概就是V1.2版本之后设定了印章透明度,之前都是不透明的

**Comment by errorcheng** [comment]
对的，就是那个透明度，能不能自定义呢？



***@***.***
 
发件人： YONG PENG
发送时间： 2022-05-21 23:57
收件人： flytkgl/PDFQFZ
抄送： errorcheng; Author
主题： Re: [flytkgl/PDFQFZ] 印章清晰度能不能自定义呢 (Issue #6)
我这边看了下提交记录,大概就是V1.2版本之后设定了印章透明度,之前都是不透明的

**Comment by flytkgl** [comment]
> 对的，就是那个透明度，能不能自定义呢？ 

自定义印章透明度已添加
