### ISSUE TITLE
多文件预览问题

### ISSUE THREAD

**Issue by btwise** [flytkgl/PDFQFZ#62]
当选择多个文件打开或选择目录模式时，在预览下拉列表框来回选择文件会出现程序错误中断，提示定位现象如下
![1727775799087](https://github.com/user-attachments/assets/52b0f91a-cb16-4fc7-a4da-171b181b3557)

**Comment by btwise** [comment]
@flytkgl 
即使选择一个文件时，如果在预览下拉列表框里来回选择，也会出现这个故障！而且预览列表框能否把那个最上面的空行删除掉？

**Comment by flytkgl** [comment]
那是因为文件预览现在是异步操作，你在文件预览没加载完的时候就切换就会报错

**Comment by btwise** [comment]
但是如果选择单个文件，代码会自动执行列表栏选择动作，预览是正常的，分页也是正常的，可以切换上一页下一页，说明加载已经完成，这个时候在点击列表框进行选择也会同样报错



---原始邮件---
发件人: "YONG ***@***.***&gt;
发送时间: 2024年10月1日(周二) 晚上7:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [flytkgl/PDFQFZ] 多文件预览问题 (Issue #62)




 
那是因为文件预览现在是异步操作，你在文件预览没加载完的时候就切换就会报错

**Comment by btwise** [comment]
@flytkgl 
这个问题的原因是:
     列表框的SelectedIndexChanged的事件手动调用 SelectionChangeCommitted，导致了多次触发相同的逻辑，尤其是在异步操作尚未完成时，又触发了新的选择事件。当 SelectedIndexChanged 事件发生时，异步加载可能尚未完成，进而导致viewPdfimgs为空或正在处理中，导致数据不一致的错误。
