### ISSUE TITLE
增加印章旋转角度功能

### ISSUE THREAD

**Issue by Eyion** [flytkgl/PDFQFZ#7]
现实中不会盖得那么正，能够调整印章角度更好？

**Comment by flytkgl** [comment]
> 现实中不会盖得那么正，能够调整印章角度更好？

1.9版本已支持调整印章角度,考虑到并不是所有印章都是圆形或正方形的图片,一般还是建议通过PS等其他手段制作一个不是那么正的印章图片,不然调整角度后很难保证印章的完整和尺寸,导致骑缝章出现异常,所有骑缝章不做支持

**Comment by flytkgl** [comment]
已支持印章和骑缝章的旋转,对椭圆形的印章可能无法完美支持,建议椭圆形印章使用自制带旋转角度的图片

**Comment by Eyion** [comment]
> 已支持印章和骑缝章的旋转,对椭圆形的印章可能无法完美支持,建议椭圆形印章使用自制带旋转角度的图片

谢谢！
