### ISSUE TITLE
如果是扣的印章怎么办呢> dpi能够修改

### ISSUE THREAD

**Issue by PANLI77** [flytkgl/PDFQFZ#8]
如果是扣的印章怎么办呢> dpi能够修改

这是因为电脑显示图片跟PDF图片的DPI不一样,之前是按PDF的DPI来显示的,会比电脑上看的小很多,所以后面改成了按电脑显示的DPI.其实提示有说明的,你只需要提供个高清点的印章图片,然后调整缩放比例或者直接指定印章尺寸就可以了

_Originally posted by @flytkgl in https://github.com/flytkgl/PDFQFZ/issues/6#issuecomment-1119312610_

**Comment by flytkgl** [comment]
> 如果是扣的印章怎么办呢> dpi能够修改
> 
> 这是因为电脑显示图片跟PDF图片的DPI不一样,之前是按PDF的DPI来显示的,会比电脑上看的小很多,所以后面改成了按电脑显示的DPI.其实提示有说明的,你只需要提供个高清点的印章图片,然后调整缩放比例或者直接指定印章尺寸就可以了
> 
> _Originally posted by @flytkgl in [#6 (comment)](https://github.com/flytkgl/PDFQFZ/issues/6#issuecomment-1119312610)_

我这边测试用一个分辨率只有113的印章图片盖章显示的效果跟直接浏览印章图片的效果是一样的.
不太清除你是怎么使用的,如果印章图片分辨率比较高,就缩小比例,分辨率本来就低的话,工具也没办法把他转成高清
无论是不是扣的印章,最简单的使用方式,你只要知道印章的实际尺寸,然后扣的时候只扣印章的部分,,然后直接设置印章尺寸为实际尺寸盖章即可

**Comment by flytkgl** [comment]
dpi就是通过缩放比例来兼容的,然后透明度现在也支持自定义了
你这问题不明确,我就先关了
